# Generated by Django 4.2.5 on 2023-10-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_address_user_age_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identification_date',
        ),
        migrations.AddField(
            model_name='user',
            name='identification_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
