# Generated by Django 4.2.5 on 2023-10-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_directory_path_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='s3_url',
        ),
    ]
