# Generated by Django 4.2.5 on 2023-10-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_file_s3_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='path',
        ),
    ]
