# Generated by Django 4.2.5 on 2023-10-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_directory_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
